query ListJobs @auth(level: PUBLIC, insecureReason: "Local testing only") {
  jobs {
    id
    title
    status
    company {
      id
      name
    }
    user {
      id
      email
      displayName
    }
  }
}

mutation CreateCompany(
  $name: String!
) @auth(level: PUBLIC, insecureReason: "Class project demo") {
  company_insert(data: {
    name: $name
  })
}

mutation CreateJob(
  $title: String!
  $status: String!
  $companyId: UUID!
) @auth(level: PUBLIC, insecureReason: "Class project demo") {
  job_insert(data: {
    title: $title
    status: $status
    company: { id: $companyId }
  })
}