query ListJobs @auth(level: PUBLIC, insecureReason: "Local testing only") {
  jobs {
    id
    title
    status
    salary
  }
}

mutation CreateJob(
  $title: String!
  $status: String!
  $salary: String
) @auth(level: PUBLIC, insecureReason: "Local testing only") {
  job_insert(data: {
    title: $title
    status: $status
    salary: $salary
  })
}

mutation UpdateJobStatus($id: UUID!, $status: String!) @auth(level: PUBLIC, insecureReason: "Local testing only") {
  job_update(id: $id, data: { status: $status })
}

mutation DeleteJob($id: UUID!) @auth(level: PUBLIC, insecureReason: "Local testing only") {
  job_delete(id: $id)
}

mutation UpdateJob($id: UUID!, $title: String!, $status: String!, $salary: String) @auth(level: PUBLIC, insecureReason: "Local testing only") {
  job_update(id: $id, data: { title: $title, status: $status, salary: $salary })
}

query ListEmployees @auth(level: PUBLIC, insecureReason: "Local testing only") {
  employees {
    id
    name
    email
    role
  }
}

query ListApplications @auth(level: PUBLIC, insecureReason: "Local testing only") {
  applications {
    id
    applicantId
    jobId
    applicant {
      id
      name
      email
    }
    job {
      id
      title
      status
      salary
    }
    salaryProposed
    status
    appliedDate
  }
}

mutation UpdateApplicationStatus($id: UUID!, $status: String!) @auth(level: PUBLIC, insecureReason: "Local testing only") {
  application_update(id: $id, data: {status: $status})
}