type Applicant @table {
    name: String!
    email: String!
}

type Job @table {
    title: String!
    status: String!
    salary: String
}

type Application @table {
    applicant: Applicant!
    job: Job!
    salaryProposed: Float
    status: String!
    appliedDate: Date!
}