type Job @table {
    title: String!
    status: String!
    salary: Float
}

type Application @table {
    name: String!
    email: String!
    job: Job!
    salaryProposed: Float
    status: String!
    appliedDate: Date!
}

type Employee @table {
    name: String!
    email: String!
    role: String!
    job: Job!
    originalApplication: Application!
}

type Interview @table {
    application: Application!
    interviewerName: String
    interviewStartDate: Timestamp
    interviewEndDate: Timestamp
    interviewModality: String
}